name: Coveralls GitHub Action(dev)

on:
  # push:
  # branches: [main]
  # pull_request:
  # branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        # (need) Node.js version
        node-version: [15.x, 16.x]

    steps:
      - name: Checkout
        # uses: actions/checkout@v2
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        # uses: actions/setup-node@v1
        uses: actions/setup-node@v3
        # id: setup_node_id
        with:
          # (need) Node.js version
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          # repo-token: ${{ github.token }}
          # repository: ${{ github.repository }}
          # GITHUB_TOKEN: ${{ github.token }}

        # (need)
      - name: npm install
        # if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
        # run: npm install
        run: npm ci

      - name: Coverage report
        run: npm run coverage-report

        # (need)
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
