name: Coveralls GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: install packages
        # uses: coverallsapp/github-action@1.1.3
        run: npm install
      - name: code coverage reqport
        run: npm cover
        with:
          github-token: ${{ secrets.github_token }}
