name: Coveralls GitHub Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        id: setup_node_id
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          repo-token: ${{ github.token }}
          repository: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
      - if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
        run: npm install
      - run: npm run coverage-report
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
