name: Coveralls GitHub Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x]

    steps:
      - uses: actions/setup-node@v3
        id: setup_node_id
        with:
          node-version: 16.14.2
          cache: npm
      - if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
        run: npm install
      - run: npm coverage-github-action
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
